In [1]:
import numpy as np
import pandas as pd

In [ ]:
provider_contracts_df = pd.read_csv('../../data/Provider contract.csv')
display(provider_contracts_df)

,Provider Name,Contract type,Shift preference,Total shift count,Weekend shift count,PM shift count
0,Miles Collins,IC,PM,6,4,6
1,Xander Mitchell,FT,"MD1, PM",16,4,4
2,Noah Stevens,IC,"MD1, PM",8,8,8
3,Riley Nelson,IC,"MD1, MD2, PM",6,6,6
4,Riley Stevens,IC,"MD1, PM",0,0,0
5,Miles Walker,FT,"MD1, PM",10,2,2
6,Spencer Stevens,FT,"MD1, PM",12,2,2
7,Spencer Adams,FT,MD2,12,4,0
8,Riley Adams,FT,"MD1, PM",14,4,4
9,Noah Brooks,IC,MD2,4,2,0
10,Jordan Davis,IC,MD2,2,2,0
11,Aiden Reed,IC,"MD1, PM",8,2,8
12,Miles Collins,FT,MD2,15,4,0
13,Parker Parker,IC,"MD1, PM",7,1,0
14,Logan Stevens,FT,"MD1, MD2, PM",15,4,4
15,Spencer Turner,IC,"MD1, MD2, PM",7,2,1
16,Theo Reed,IC,MD2,4,2,0
17,Theo Lewis,FT,MD2,15,4,0
18,Aiden Evans,IC,MD2,7,2,0
19,Jordan Brooks,IC,PM,3,1,3
20,Miles Keller,FT,"MD1, PM",15,4,4
21,Miles Foster,FT,MD2,15,4,0
22,Spencer Irving,IC,MD2,7,2,0
23,Spencer Davis,FT,"MD1, PM",15,4,15
24,Quinn Turner,IC,MD2,7,2,0
25,Aiden Adams,IC,MD2,6,2,0
26,Aiden Davis,IC,"MD1, PM",7,2,1
27,Spencer Nelson,IC,"MD1, PM",7,2,1
28,Dylan Nelson,FT,"MD1, PM",15,4,15
29,Noah Parker,IC,MD2,7,2,0
30,Jordan Collins,IC,"MD1, PM",7,2,2
31,Jordan Turner,FT,MD2,15,4,0
32,Logan Collins,FT,MD2,15,4,0
33,Cameron Collins,FT,MD2,14,4,0
34,Kai Keller,FT,"MD1, PM",15,4,15
35,Riley Davis,IC,MD2,7,2,0
36,Miles Collins,IC,MD2,7,2,0
37,Hayden Reed,FT,"MD1, PM",15,4,2
38,Parker Young,IC,MD2,7,2,0
39,Riley Hughes,IC,MD2,7,2,0
40,Jordan Mitchell,IC,MD2,7,2,1
41,Riley Keller,FT,"MD1, PM",15,0,5
42,Theo Gibson,IC,"MD1, PM",6,1,3
43,Aiden Davis,IC,MD2,7,2,0
44,Cameron Walker,IC,"MD1, PM",7,2,7
45,Aiden Walker,IC,"MD1, MD2, PM",7,2,1
46,Spencer Adams,IC,"MD1, MD2, PM",7,2,7
47,Jordan Irving,IC,"MD1, MD2",7,2,0

In [12]:
import re
from typing import List, Dict, Tuple, Set


SHIFT_ALIASES = {
    "MD1": "MD1",
    "MD2": "MD2",
    "PM": "PM",
    # (If you ever feed "AM" in, treat as both MD1 & MD2)
    "AM": "AM",
    "AM ONLY": "AM",
    "PM ONLY": "PM",
}

def normalize_provider(name: str) -> str:
    return re.sub(r"\s+", " ", name.strip())

def normalize_facility(name: str) -> str:
    return name.strip()

def parse_shift_list(s: str) -> Set[str]:
    """
    Normalize and expand shift preference strings like:
      "MD1, PM" -> {"MD1","PM"}
      "MD1, MD2, PM" -> {"MD1","MD2","PM"}
      "AM" -> {"MD1","MD2"}   (treat AM as both day shifts)
    """
    if pd.isna(s):
        return set()
    parts = [p.strip().upper() for p in str(s).split(",")]
    out = set()
    for p in parts:
        p = SHIFT_ALIASES.get(p, p)
        if p == "AM":
            out.update({"MD1", "MD2"})
        elif p in {"MD1","MD2","PM"}:
            out.add(p)
    return out

def read_provider_contracts(contracts_df) -> pd.DataFrame:
    # Normalize provider names
    contracts_df["provider_name"] = contracts_df["Provider Name"].map(normalize_provider)
    # Normalize shift preferences to sets
    contracts_df["shift_set"] = contracts_df["Shift preference"].apply(parse_shift_list)
    # There may be duplicate provider rows → union their shift sets
    pref = (
        contracts_df.groupby("provider_name", as_index=False)
          .agg(shift_set=("shift_set", lambda sets: set().union(*sets)))
    )
    # Optional: keep a canonical contract type (FT over IC if both present)
    def pick_contract(group):
        types = set(group["Contract type"].dropna().str.upper())
        if "FT" in types:
            return "FT"
        if "IC" in types:
            return "IC"
        return group["Contract type"].iloc[0] if len(group) else None

    pref["contract_type"] = (
        contracts_df.groupby("provider_name")
          .apply(pick_contract)
          .reindex(pref["provider_name"])
          .values
    )
    # Keep the raw counts if you want later (union not needed here)
    return pref

In [13]:
display(read_provider_contracts(provider_contracts_df))

/var/folders/0x/9v5q2xwj44327h79d29_npbw0000gn/T/ipykernel_67929/2187258195.py:61: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(pick_contract)

      provider_name       shift_set contract_type
0       Aiden Adams           {MD2}            IC
1       Aiden Davis  {MD2, MD1, PM}            IC
2       Aiden Evans           {MD2}            IC
3        Aiden Reed       {MD1, PM}            IC
4      Aiden Walker  {MD2, MD1, PM}            IC
5   Cameron Collins           {MD2}            FT
6    Cameron Walker       {MD1, PM}            IC
7      Dylan Nelson       {MD1, PM}            FT
8       Hayden Reed       {MD1, PM}            FT
9     Jordan Brooks            {PM}            IC
10   Jordan Collins       {MD1, PM}            IC
11     Jordan Davis           {MD2}            IC
12    Jordan Irving      {MD2, MD1}            IC
13  Jordan Mitchell           {MD2}            IC
14    Jordan Turner           {MD2}            FT
15       Kai Keller       {MD1, PM}            FT
16    Logan Collins           {MD2}            FT
17    Logan Stevens  {MD2, MD1, PM}            FT
18    Miles Collins       {MD2, PM}            FT
19     Miles Foster           {MD2}            FT
20     Miles Keller       {MD1, PM}            FT
21     Miles Walker       {MD1, PM}            FT
22      Noah Brooks           {MD2}            IC
23      Noah Parker           {MD2}            IC
24     Noah Stevens       {MD1, PM}            IC
25    Parker Parker       {MD1, PM}            IC
26     Parker Young           {MD2}            IC
27     Quinn Turner           {MD2}            IC
28      Riley Adams       {MD1, PM}            FT
29      Riley Davis           {MD2}            IC
30     Riley Hughes           {MD2}            IC
31     Riley Keller       {MD1, PM}            FT
32     Riley Nelson  {MD2, MD1, PM}            IC
33    Riley Stevens       {MD1, PM}            IC
34    Spencer Adams  {MD2, MD1, PM}            FT
35    Spencer Davis       {MD1, PM}            FT
36   Spencer Irving           {MD2}            IC
37   Spencer Nelson       {MD1, PM}            IC
38  Spencer Stevens       {MD1, PM}            FT
39   Spencer Turner  {MD2, MD1, PM}            IC
40      Theo Gibson       {MD1, PM}            IC
41       Theo Lewis           {MD2}            FT
42        Theo Reed           {MD2}            IC
43  Xander Mitchell       {MD1, PM}            FT

In [ ]:
provider_credentials_df = pd.read_csv('../../data/Provider Credentialing.csv')
display(provider_credentials_df)

,Provider,Credentialed Facilities,Unnamed: 2
0,Xander Mitchell,"RMC, WREC, WRMC, Wraleigh, Wcary, wplex, Wgarn...",NaN
1,Riley Nelson,"RMC, WREC, WRMC, Wraleigh, Wcary, wplex, Wgarn...",NaN
2,Spencer Stevens,"RMC, WREC, WRMC, Wraleigh, Wcary, wplex, Wgarn...",NaN
3,Riley Adams,"RMC, Wraleigh, Wcary, wplex, Wgarner, Wbrier, ...",NaN
4,Miles Collins,"RMC, WREC, WRMC, Wraleigh, Wcary, wplex, Wgarn...",NaN
5,Noah Stevens,"WREC, WRMC, Wraleigh, Wcary, wplex, Wgarner, W...",NaN
6,Riley Stevens,"RMC, WREC, WRMC, Wraleigh, Wcary, wplex, Wgarn...",NaN
7,Miles Walker,"RMC, WREC, WRMC, Wraleigh, Wcary, wplex, Wgarn...",NaN
8,Spencer Adams,"RMC, Hfax, Hbal, Smain, HM, HB, FMain, FD, FF,...",NaN
9,Noah Brooks,"Hfax, Smain, HM, HB, FMain, FD, FF, FM, SD, ST...",NaN
10,Jordan Davis,"Hbal, Smain, HM, HB, FMain, FD, FF, FM, SD, SM...",NaN
11,Aiden Reed,"WREC, WRMC, Wraleigh, Wcary, wplex, Wgarner, W...",NaN
12,Miles Collins,"RMC, Hfax, Smain, HM, HB, FMain, FD, FF, FM, S...",NaN
13,Parker Parker,"Wraleigh, Wcary, wplex, Wgarner, Wbrier, Wnort...",NaN
14,Logan Stevens,"RMC, WREC, WRMC, Wraleigh, Wcary, wplex, Wgarn...",NaN
15,Spencer Turner,"Wraleigh, Wcary, wplex, Wgarner, Wbrier, Wnort...",NaN
16,Theo Reed,"HM, HB, AHG, AHM, NMHMC, NMMC, NBAMC, NBRMC, N...",NaN
17,Theo Lewis,"RMC, Hfax, Hbal, HM, HB, N, RHR, RHC, SDH, WCC...",NaN
18,Aiden Evans,"Wraleigh, Wcary, wplex, Wgarner, Wbrier, Wnort...",NaN
19,Jordan Brooks,"Wraleigh, Wcary, wplex, Wgarner, Wbrier, Wnort...",NaN
20,Miles Keller,"RMC, WREC, WRMC, Wraleigh, Wcary, wplex, Wgarn...",NaN
21,Miles Foster,"Hfax, Hbal, NNSMC, HM, HB, NMHMC, NMMC, NBAMC,...",NaN
22,Spencer Irving,"FNHM, SSMM",NaN
23,Spencer Davis,"Wraleigh, Wcary, wplex, Wgarner, Wbrier, Wnort...",NaN
24,Quinn Turner,"NMMC, NBAMC, NBRMC, NHMC, NRMC, NTMC, RRMC, RS...",NaN
25,Aiden Adams,"NMMC, NBAMC, NBRMC, NHMC, NRMC, NTMC, FGHM, FC...",NaN
26,Aiden Davis,"HB, RHR, RHC, AHG, AHM, CHLGHV, CHSCHV, CHBMHV...",NaN
27,Spencer Nelson,"FD, FWK, FCWay, FCW, FF, FM, VV, VM, VMH, VW, ...",NaN
28,Dylan Nelson,"WREC, WRMC, Wraleigh, Wcary, wplex, Wgarner, W...",NaN
29,Noah Parker,"FD, FWK, FCWay, FCW, FF, FM, BHJCMC, BHBRMC, B...",NaN
30,Jordan Collins,"Smain, HM, HB, SD, ST, SM, VV, VM, VMH, VW, VB...",NaN
31,Jordan Turner,"NNSMC, N, RHR, RHC, NMHMC, NMMC, NBAMC, NHMC, ...",NaN
32,Logan Collins,"NNSMC, HM, HB, FMain, FD, FF, FM, N, RHR, RHC,...",NaN
33,Cameron Collins,"NNSMC, HM, HB, RHR, RHC, WCCH, NMHMC, NMMC, NB...",NaN
34,Kai Keller,"Hbal, FMain, FD, FF, FM, WCCH, CHLGHV, CHSCHV,...",NaN
35,Riley Davis,"RHR, RHC, NMHMC, NMMC, NBAMC, NHMC, NRMC, NNDR...",NaN
36,Miles Collins,"NMMC, NBAMC, NBRMC, NHMC, NRMC, NTMC, RMC",NaN
37,Hayden Reed,"WREC, WRMC, Wraleigh, Wcary, wplex, Wgarner, W...",NaN
38,Parker Young,"NNSMC, RHR, RHC, NNDRF, EHBHB, EHBH, EHCH, EHE...",NaN
39,Riley Hughes,"RHC, BHJCMC, BHBRMC, BHHVMC, BHIPCH, BHJMHV, B...",NaN
40,Jordan Mitchell,"MMC, N, AHG, AHM, SRGH, SROSH, SRPH, FGHM, FCH...",NaN
41,Riley Keller,"Wraleigh, Wcary, wplex, Wgarner, Wbrier, Wnort...",NaN
42,Theo Gibson,"FD, FWK, FCWay, FCW, FF, FM, TM, TNF, TD, TCL,...",NaN
43,Aiden Davis,"NNDRF, CMMC, CMBH, CMRH, NNEMN, NNESS, NNMC, SSMM",NaN
44,Cameron Walker,"Hbal, Smain, SD, ST, TM, TNF, TD, TCL, WCCH, C...",NaN
45,Aiden Walker,"TM, TNF, TD, TCL, WCCH, SJUMC, SJWMC, CMMC, CM...",NaN
46,Spencer Adams,"NHC, NHD, NHF, NHG, BHJCMC",NaN
47,Jordan Irving,"BHBRMC, BHHVMC, BHIPCH, BHJMHV, BHFWCH, BHGCHT...",NaN
48,NaN,NaN,NaN
49,NaN,NaN,NaN
50,NaN,NaN,NaN
51,NaN,NaN,NaN

In [16]:
def read_provider_credentials(credentials_df) -> pd.DataFrame:
    credentials_df.columns = [c.strip() for c in credentials_df.columns]
    credentials_df["Provider"] = credentials_df["Provider"].map(normalize_provider)
    # Some rows may be empty at the end
    credentials_df = credentials_df.dropna(subset=["Provider"]).copy()

    def split_facilities(s: str) -> Set[str]:
        if pd.isna(s) or not str(s).strip():
            return set()
        # split by comma, strip whitespace
        return {normalize_facility(x) for x in str(s).split(",")}
    credentials_df["facility_set"] = credentials_df["Credentialed Facilities"].apply(split_facilities)

    # Deduplicate by union of facility sets across repeated providers
    cred = (
        credentials_df.groupby("Provider", as_index=False)
          .agg(facility_set=("facility_set", lambda sets: set().union(*sets)))
    )
    return cred

In [17]:
display(read_provider_credentials(provider_contracts_df))

KeyError: 'Provider'